version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.full
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./prototypes/.env:/app/prototypes/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.full
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_URL=http://backend:8000
    restart: unless-stopped

networks:
  default:
    name: nutrigraph-full
